name: Update release draft
on:
  push:
    branches:
      - master

jobs:
  release-draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.DEPLOY_APP_ID }}
          private-key: ${{ secrets.DEPLOY_APP_KEY }}

      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
