name: Releases binary

on:
  push:
    tags:
      - "*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: vars
        run: |
          echo ::set-output name=go_version::$(cat go.mod | head -3 | tail -1 | cut -d ' ' -f 2)
          echo "Using Go version ${{ steps.vars.outputs.go_version }}"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.vars.outputs.go_version }}

      - name: Compile the source
        uses: goreleaser/goreleaser-action@v6
        with:
          version: v2.1.0
          args: release
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
