name: Publish Brew release

on:
  push:
    tags:
      - "*"

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest

    steps:
      # Documentation here
      # https://github.com/mislav/bump-homebrew-formula-action?tab=readme-ov-file#action-inputs
      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          commit-message: "feat({z{formulaName}}): publish version {{version}} 🤖"
          formula-path: kubernetes-labels-migrator.rb
          homebrew-tap: Tchoupinax/homebrew-brew
        env:
          COMMITTER_TOKEN: ${{ secrets.BREW_PUBLISH_TOKEN }}
